/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uam.pvoe.sw.formas;

import java.util.LinkedList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import uam.pvoe.atributos.Editorial;
import uam.pvoe.atributos.Libros;
import uam.pvoe.atributos.Revistas;
import uam.pvoe.operaciones.OperacionesConsultas;
import uam.pvoe.operaciones.RegistroEditorial;
import uam.pvoe.operaciones.RegistroLibro;
import uam.pvoe.operaciones.RegistroRevista;

/**
 *
 * @author Guerrero Cangas Sebastian
 * Proyecto final
 */
public class FrConsultas extends javax.swing.JFrame {

    /**
     * Creates new form FrConsultas
     */
    public FrConsultas() {
        initComponents();
        llenarTablaInicial();
        agruparSelecciones();
        llenarListaEditorial();
        /**
         * llamamos las funciones
         */
    }

     private void llenarTablaInicial(){
        DefaultTableModel modelo = new DefaultTableModel(0,0);//tabla basica
        
        OperacionesConsultas tabla = new OperacionesConsultas();//llamamos el metodo
        
        Libros lil = new Libros();
        Revistas rev = new Revistas();
        
        Vector filas = new Vector();//creamos un vector
        Vector columna = new Vector();//creamos el vector de la columna
        
        RegistroLibro regli = new RegistroLibro();
        RegistroRevista regre = new RegistroRevista();
        /*
        convocamos la funciones de la clase
        registrolibro y registro revista
        */
        int p = regre.listaR().size();//el tamaño de la lista
        filas = tabla.elementosCeldaR(p,p);
        //la llenamos de filas
        columna = tabla.tituloColumnasR();//llenamos de la columna 
        
        modelo.setDataVector(filas, columna);//se lo mandamos a la tabla nueva
        
        tblInfo.setModel(modelo);//convocamos la tabla generica sin informacion
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgLibroR = new javax.swing.ButtonGroup();
        lblQue = new javax.swing.JLabel();
        rbLibro = new javax.swing.JRadioButton();
        rbRevista = new javax.swing.JRadioButton();
        lblEditorial = new javax.swing.JLabel();
        txtEditorial = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInfo = new javax.swing.JTable();
        cmbEditorial = new javax.swing.JComboBox<>();
        btnMenu = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblQue.setText("Que es ?");

        rbLibro.setText("Libro");

        rbRevista.setText("Revista");

        lblEditorial.setText("Editorial");

        tblInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblInfo);

        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblEditorial)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbLibro)
                        .addGap(18, 18, 18)
                        .addComponent(rbRevista))
                    .addComponent(lblQue)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblQue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbLibro)
                    .addComponent(rbRevista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEditorial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMenu)
                    .addComponent(btnLimpiar))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        FrMenu menu = new FrMenu();
        this.dispose();
        menu.setVisible(true);
        /**
         * llamamos al menu, para que aparezca y cierre esta 
         */
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        
        if(rbLibro.isSelected()==true){//por si el rb libro esta activado
        
            DefaultTableModel modelo = new DefaultTableModel(0,0);//tabla basica
        
            OperacionesConsultas tabla = new OperacionesConsultas();//llamamos el metodo

            Libros lil = new Libros();
            
            Vector filas = new Vector();//creamos un vector
            Vector columna = new Vector();//creamos el vector de la columna

            RegistroLibro regli = new RegistroLibro();
      
            int p = regli.listaL().size();
            filas = tabla.elementosCeldaL(p,p);
            //la llenamos de filas
            columna = tabla.tituloColumnasL();//llenamos de la columna 

            modelo.setDataVector(filas, columna);//se lo mandamos a la tabla nueva

            tblInfo.setModel(modelo);//convocamos la tabla generica sin informacion

        }else if(rbRevista.isSelected()==true){//por si la rb revista esta activada
            DefaultTableModel modelo = new DefaultTableModel(0,0);//tabla basica
        
            OperacionesConsultas tabla = new OperacionesConsultas();//llamamos el metodo

            Revistas rev = new Revistas();
        
            Vector filas = new Vector();//creamos un vector
            Vector columna = new Vector();//creamos el vector de la columna

            RegistroRevista regre = new RegistroRevista();
                /*
                convocamos la funciones de la clase
                cargararchivos
                */
            int p = regre.listaR().size();
            filas = tabla.elementosCeldaR(p,p);
                //la llenamos de filas
            columna = tabla.tituloColumnasR();//llenamos de la columna 

            modelo.setDataVector(filas, columna);//se lo mandamos a la tabla nueva

            tblInfo.setModel(modelo);//convocamos la tabla generica sin informacion

        }
        
    }//GEN-LAST:event_btnConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrConsultas().setVisible(true);
            }
        });
    }

    
    public void agruparSelecciones(){
        btgLibroR.add(rbLibro);
        btgLibroR.add(rbRevista);
        
        /**
         * para hacerlos mutuamente excluyentes
         */
    } 
    
     public void llenarListaEditorial(){
        RegistroEditorial edi=new RegistroEditorial();/**
         * llamamos la clase RegistroEditorial
         */
        
        LinkedList<Editorial> Lista=edi.listaEditorial();/**
         * generamos una lista ligada de editoriales
         */
        for(int i=0; i<Lista.size(); i++){
            //Toma la informacion del toString para poner las etiquetas en la interfaz
            cmbEditorial.addItem(Lista.get(i));//se lo ingresamos como objetos, a combobox
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgLibroR;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JComboBox<Editorial> cmbEditorial;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEditorial;
    private javax.swing.JLabel lblQue;
    private javax.swing.JRadioButton rbLibro;
    private javax.swing.JRadioButton rbRevista;
    private javax.swing.JTable tblInfo;
    private javax.swing.JTextField txtEditorial;
    // End of variables declaration//GEN-END:variables
}
