/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uam.pvoe.sw.formas;

import java.util.LinkedList;
import java.util.Vector;
import javax.swing.JRadioButton;
import javax.swing.table.DefaultTableModel;
import uam.pvoe.atributos.Cliente;
import uam.pvoe.atributos.Editorial;
import uam.pvoe.atributos.Libros;
import uam.pvoe.atributos.PrestamosRevista;
import uam.pvoe.atributos.Revistas;
import uam.pvoe.operaciones.OperacionesConsultaPrestamo;
import uam.pvoe.operaciones.OperacionesConsultas;
import uam.pvoe.operaciones.RegistroCliente;
import uam.pvoe.operaciones.RegistroEditorial;
import uam.pvoe.operaciones.RegistroLibro;
import uam.pvoe.operaciones.RegistroPrestamosLibro;
import uam.pvoe.operaciones.RegistroRevista;
import uam.pvoe.operaciones.RegistrosPrestamosRevista;

/**
 *
 * @author Guerrero Cangas Sebastian
 * proyecto final
 */
public class FrConsultasPrestamos extends javax.swing.JFrame {

    /**
     * Creates new form FrSeguimientoCliente
     */
    public FrConsultasPrestamos() {
        initComponents();
        llenarTablaInicial();
        agruparSelecciones();
        llenarListaCliente();
        /**
         * llamamos la funcion
         */
    }

    private void llenarTablaInicial(){//esto es para tabla generica
        DefaultTableModel modelo = new DefaultTableModel(0,0);//tabla basica
        
        OperacionesConsultaPrestamo tabla = new OperacionesConsultaPrestamo();//llamamos el metodo
        
        Libros lil = new Libros();
        Revistas rev = new Revistas();
        
        Vector filas = new Vector();//creamos un vector
        Vector columna = new Vector();//creamos el vector de la columna
        
        RegistroPrestamosLibro regli = new RegistroPrestamosLibro();
        RegistrosPrestamosRevista rul = new RegistrosPrestamosRevista();
        /**
         * convocados para poder generar la tabla necesaria
         */
        
        int p=regli.listaLPGenerica().size();//le pasamos el tamaño de la cadena
        
        filas = tabla.elementosCeldaLGenerico(p,p);
        //la llenamos de filas
        columna = tabla.tituloColumnasL();//llenamos de la columna 
        
        modelo.setDataVector(filas, columna);//se lo mandamos a la tabla nueva
        
        tblInfo.setModel(modelo);//convocamos la tabla generica sin informacion
        lblMensaje.setText("tabla generica");
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgLibroR = new javax.swing.ButtonGroup();
        lblNomCli = new javax.swing.JLabel();
        cmbNomCli = new javax.swing.JComboBox<>();
        lblCurp = new javax.swing.JLabel();
        lblSolitar = new javax.swing.JLabel();
        rbRevista = new javax.swing.JRadioButton();
        rbLibro = new javax.swing.JRadioButton();
        pnlCuadro = new javax.swing.JScrollPane();
        tblInfo = new javax.swing.JTable();
        btnLimpiar = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        btnPrestamoLibro = new javax.swing.JButton();
        btnPrestamoRevista = new javax.swing.JButton();
        lblMosCurp = new javax.swing.JLabel();
        lblMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblNomCli.setText("Nombre de los Clientes registrados");

        cmbNomCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNomCliActionPerformed(evt);
            }
        });

        lblCurp.setText("CURP");

        lblSolitar.setText("Solicitar");

        rbRevista.setText("Revista");
        rbRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRevistaActionPerformed(evt);
            }
        });

        rbLibro.setText("Libro");
        rbLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLibroActionPerformed(evt);
            }
        });

        tblInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        pnlCuadro.setViewportView(tblInfo);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        btnPrestamoLibro.setText("Registrar Prestamo libro");
        btnPrestamoLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestamoLibroActionPerformed(evt);
            }
        });

        btnPrestamoRevista.setText("Registrar Prestamo Revista");
        btnPrestamoRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestamoRevistaActionPerformed(evt);
            }
        });

        lblMensaje.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLimpiar)
                        .addGap(18, 18, 18)
                        .addComponent(btnMenu)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrestamoLibro)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrestamoRevista))
                    .addComponent(pnlCuadro, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSolitar)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNomCli)
                                    .addComponent(cmbNomCli, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbRevista)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbLibro)))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMensaje)
                                    .addComponent(lblCurp)
                                    .addComponent(lblMosCurp))))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSolitar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbRevista)
                    .addComponent(rbLibro)
                    .addComponent(lblMensaje))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomCli)
                    .addComponent(lblCurp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbNomCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMosCurp))
                .addGap(18, 18, 18)
                .addComponent(pnlCuadro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnMenu)
                    .addComponent(btnPrestamoLibro)
                    .addComponent(btnPrestamoRevista))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        FrMenu menu = new FrMenu();
        this.dispose();
        menu.setVisible(true);
        /**
         * podemos abrir la pestaña del menu
         */
    }//GEN-LAST:event_btnMenuActionPerformed

    private void cmbNomCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNomCliActionPerformed
        // TODO add your handling code here:
        int indice=cmbNomCli.getSelectedIndex(); //Recupera el indice empezando desde cero
        DefaultTableModel modelo = new DefaultTableModel(0,0);//tabla basica
        
        Cliente opcion =(Cliente) cmbNomCli.getSelectedItem();/**
         * la lista que tiene de seleccion el combobox de Cliente
         * podra cambiar
         */  
        
        RegistroCliente arc = new RegistroCliente();/**
         * convocamos la funciones de la clase
         * RegistroCliente
         */
        
        OperacionesConsultaPrestamo tabla = new OperacionesConsultaPrestamo();//llamamos el metodo
        
        RegistroPrestamosLibro regli = new RegistroPrestamosLibro();
        RegistrosPrestamosRevista rul = new RegistrosPrestamosRevista();
        
        rul.listaRP(opcion.getCurp());
        regli.listaLP(opcion.getCurp());
        /*
        mandamos la curp a las listas para que puedan delimitar
        */
        PrestamosRevista revl = new PrestamosRevista();
       
        Vector filas = new Vector();//creamos un vector
        Vector columna = new Vector();//creamos las columnas
        
        RegistrosPrestamosRevista preR = new RegistrosPrestamosRevista();/**
          * convocamos las funciones de la clase
          * de RegistrosPrestamosRevista
          */
            if(opcion.getNombre().compareTo("--Selecciona el cliente--")==0){//pone en blanco la lbl
                lblMosCurp.setText("");
            }else{
                lblMosCurp.setText(opcion.getCurp());//lo llenamos con la curp la lbl
            }
       
            if(opcion.getCurp().compareTo(opcion.getCurp())==0){//para poder comparar con curp
                 if(rbRevista.isSelected()==true){//si el rb esta activado
                     
                    int p=rul.listaRP(opcion.getCurp()).size();//le pasamos el tamaño de la cadena
                    columna = tabla.tituloColumnasR();//llenamos de la columna 
                    filas = tabla.elementosCeldaR(p, p,opcion.getCurp());
                    modelo.setDataVector(filas, columna);//se lo mandamos a la tabla nueva
                    tblInfo.setModel(modelo);//convocamos la tabla generica sin informacion
                    lblMensaje.setText("tabla de prestamos de revistas");
               }
            }
            if(opcion.getCurp().compareTo(opcion.getCurp())==0){//le pasamos el tamaño de la cadena
                 if(rbLibro.isSelected()==true){//si el rb esta activado
                    int p=regli.listaLP(opcion.getCurp()).size();//le pasamos el tamaño de la cadena
                    columna = tabla.tituloColumnasL();//llenamos de la columna 
                    filas = tabla.elementosCeldaL(p, p,opcion.getCurp());
                    modelo.setDataVector(filas, columna);//se lo mandamos a la tabla nueva
                    tblInfo.setModel(modelo);//convocamos la tabla generica sin informacion
                    lblMensaje.setText("tabla de prestamos de libros");
               }
            }
                
    }//GEN-LAST:event_cmbNomCliActionPerformed

    private void rbLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLibroActionPerformed
        // TODO add your handling code here:
       cmbNomCli.setSelectedIndex(0);/**
          * regrasamos el combo box a su primer elemento 
          */
    }//GEN-LAST:event_rbLibroActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarRb();
        cmbNomCli.setSelectedIndex(0);
        /**
         * limpiar radio boton
         */
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void rbRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRevistaActionPerformed
        // TODO add your handling code here:
         cmbNomCli.setSelectedIndex(0);/**
          * regrasamos el combo box a su primer elemento 
          */
         
    }//GEN-LAST:event_rbRevistaActionPerformed

    private void btnPrestamoLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestamoLibroActionPerformed
        // TODO add your handling code here:
        FrLibroPrestamo Lpres = new FrLibroPrestamo();
        this.dispose();
        Lpres.setVisible(true);
        /**
         * con esto podemos abrir la pestaña de libro de prestamo
         */
    }//GEN-LAST:event_btnPrestamoLibroActionPerformed

    private void btnPrestamoRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestamoRevistaActionPerformed
        // TODO add your handling code here:
        FrRevistaPrestamo Rpres = new FrRevistaPrestamo();
        this.dispose();
        Rpres.setVisible(true);
        /**
         * con esto podemos abrir la pestaña de libro de prestamo
         */
    }//GEN-LAST:event_btnPrestamoRevistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrConsultasPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrConsultasPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrConsultasPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrConsultasPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrConsultasPrestamos().setVisible(true);
            }
        });
    }

    public void agruparSelecciones(){
        btgLibroR.add(rbLibro);
        btgLibroR.add(rbRevista);
        
        /**
         * para hacerlos mutuamente excluyentes
         */
    }
    public void limpiarRb(){
        btgLibroR.clearSelection();/**
         * para poder limpiar los radio boton
         */
    }
    
     public void llenarListaCliente(){
        RegistroCliente cli=new RegistroCliente();/**
         * llamamos la clase registro cliente
         */
        
        LinkedList<Cliente> Lista=cli.listaCliente();/**
         * generamos una lista ligada de Cliente
         */
        for(int i=0; i<Lista.size(); i++){
            //Toma la informacion del toString para poner las etiquetas en la interfaz
            cmbNomCli.addItem(Lista.get(i));//se lo ingresamos como objetos, a combobox
        }
        
    }
    
    
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgLibroR;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnPrestamoLibro;
    private javax.swing.JButton btnPrestamoRevista;
    private javax.swing.JComboBox<Cliente> cmbNomCli;
    private javax.swing.JLabel lblCurp;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblMosCurp;
    private javax.swing.JLabel lblNomCli;
    private javax.swing.JLabel lblSolitar;
    private javax.swing.JScrollPane pnlCuadro;
    private javax.swing.JRadioButton rbLibro;
    private javax.swing.JRadioButton rbRevista;
    private javax.swing.JTable tblInfo;
    // End of variables declaration//GEN-END:variables
}
