/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uam.pvoe.sw.formas;

import java.util.LinkedList;
import uam.pvoe.atributos.Cliente;
import uam.pvoe.atributos.Libros;
import uam.pvoe.atributos.PrestamoLibro;
import uam.pvoe.atributos.PrestamosRevista;
import uam.pvoe.atributos.Revistas;
import uam.pvoe.operaciones.RegistroCliente;
import uam.pvoe.operaciones.RegistroLibro;
import uam.pvoe.operaciones.RegistroPrestamosLibro;
import uam.pvoe.operaciones.RegistroRevista;
import uam.pvoe.operaciones.RegistrosPrestamosRevista;

/**
 *
 * @author Guerrero Cangas Sebastian
 * proyecto final 
 */
public class FrInformacionCliente extends javax.swing.JFrame {

    /**
     * Creates new form FrInformacionCliente
     */
    public FrInformacionCliente() {
        initComponents();
        llenarListaCliente();
        llenarListaRevista();
        llenarlistaLibro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApellidoPa = new javax.swing.JLabel();
        txtApellidoPa = new javax.swing.JTextField();
        lblApellidoMa = new javax.swing.JLabel();
        txtApellidoMa = new javax.swing.JTextField();
        btnInformacion = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lblLibro = new javax.swing.JLabel();
        lblRevista = new javax.swing.JLabel();
        cmbLibro = new javax.swing.JComboBox<>();
        cmbRevista = new javax.swing.JComboBox<>();
        btnMenu = new javax.swing.JButton();
        lblNombreCliente = new javax.swing.JLabel();
        cmbCliente = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblNombre.setText("Nombre");

        lblApellidoPa.setText("Apellido Paterno");

        lblApellidoMa.setText("Apellido Materno");

        btnInformacion.setText("INFORMACION");
        btnInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformacionActionPerformed(evt);
            }
        });

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lblLibro.setText("Libro solicitados");

        lblRevista.setText("Revistas Solicitadas");

        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        lblNombreCliente.setText("Nombre de los clientes");

        cmbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombre)
                                    .addComponent(btnInformacion)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblApellidoPa)
                                            .addComponent(txtApellidoPa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtApellidoMa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblApellidoMa)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(btnLimpiar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(btnMenu)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLibro)
                                    .addComponent(cmbLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRevista)
                                    .addComponent(cmbRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreCliente)
                            .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombreCliente)
                .addGap(18, 18, 18)
                .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblApellidoPa)
                    .addComponent(lblApellidoMa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoPa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInformacion)
                    .addComponent(btnLimpiar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLibro)
                    .addComponent(lblRevista))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbRevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnMenu)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        FrMenu menu = new FrMenu();
        this.dispose();
        menu.setVisible(true); 
        /**
         * llamamos la pestaña del menu
         * cerramos esta
         */
    }//GEN-LAST:event_btnMenuActionPerformed

    private void cmbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClienteActionPerformed
        // TODO add your handling code here:
        
        int indice=cmbCliente.getSelectedIndex(); //Recupera el indice empezando desde cero
        Cliente opcion =(Cliente) cmbCliente.getSelectedItem();/**
         * la lista que tiene de seleccion el combobox de Cliente
         * podra cambiar y se guardara en el elemento 
         */  
        RegistroCliente arc = new RegistroCliente();/**
         * convocamos la funciones de la clase
         * RegistroCliente
         */
        
        if(opcion.getNombre().compareTo("--Selecciona el cliente--")==0){
            //mantenemos las caja limpia
            txtNombre.setText("");
        }else{
            //le agregamoms el  nombre a la caja de texto
            txtNombre.setText(opcion.getNombre());
        }
        if(opcion.getApellidoP().compareTo("--Selecciona el cliente--")==0){
            //mantenemos las caja limpia
            txtApellidoPa.setText("");
        }else{
            //le agregamoms el Apellido paterno a la caja de texto
            txtApellidoPa.setText(opcion.getApellidoP());
        }
        if(opcion.getApellidoM().compareTo("--Selecciona el cliente--")==0){
            //mantenemos las caja limpia
            txtApellidoMa.setText("");
        }else{
            //le agregamoms el Apellido materno a la caja de texto
            txtApellidoMa.setText(opcion.getApellidoM());
        }
        if(opcion.getNombre().compareTo("--Selecciona el cliente--")!=0 && 
                opcion.getApellidoM().compareTo("--Selecciona el cliente--")!=0
                && opcion.getApellidoP().compareTo("--Selecciona el cliente--")!=0 &&
                opcion.getCurp().compareTo("--Selecciona el cliente--")!=0){
            cmbCliente.removeAllItems();
            llenarListaCliente();
            /**
             * si es difirente se borra la caja de texto y vuelve cargar la lista
             */
        }
    }//GEN-LAST:event_cmbClienteActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformacionActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btnInformacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrInformacionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrInformacionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrInformacionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrInformacionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrInformacionCliente().setVisible(true);
            }
        });
    }
    
    private void limpiar(){
        txtNombre.setText("");
        txtApellidoPa.setText("");
        txtApellidoMa.setText("");
    }
    
    private void llenarListaCliente(){
        RegistroCliente cli=new RegistroCliente();/**
         * llamamos la clase RegistroCliente
         */
        
        LinkedList<Cliente> Lista=cli.listaCliente();/**
         * generamos una lista ligada de Cliente, que le agregara la lista
         * de la clase RegistroCliente
         */
        for(int i=0; i<Lista.size(); i++){
            //Toma la informacion del toString para poner las etiquetas en la interfaz
            cmbCliente.addItem(Lista.get(i));//se lo ingresamos como objetos, a combobox
        }
    }
    
    private void llenarListaRevista(){
        
        RegistroRevista cli=new RegistroRevista();/**
         * llamamos la clase registrorevitaa
         */
        
        LinkedList<Revistas> Lista=cli.listaR();/**
         * generamos una lista ligada de Revistas, que le agregara la lista
         * de la clase RegistroRevista
         */
        for(int i=0; i<Lista.size(); i++){
            //Toma la informacion del toString para poner las etiquetas en la interfaz
            cmbRevista.addItem(Lista.get(i));//se lo ingresamos como objetos, a combobox
        }
    }
    
    private void llenarlistaLibro(){
        RegistroLibro cli=new RegistroLibro();/**
         * llamamos la clase RegistroLibro
         */
        
        LinkedList<Libros> Lista=cli.listaL();/**
         * generamos una lista ligada de Libros
         */
        for(int i=0; i<Lista.size(); i++){
            //Toma la informacion del toString para poner las etiquetas en la interfaz
            cmbLibro.addItem(Lista.get(i));//se lo ingresamos como objetos, a combobox
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInformacion;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JComboBox<Cliente> cmbCliente;
    private javax.swing.JComboBox<Libros> cmbLibro;
    private javax.swing.JComboBox<Revistas> cmbRevista;
    private javax.swing.JLabel lblApellidoMa;
    private javax.swing.JLabel lblApellidoPa;
    private javax.swing.JLabel lblLibro;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblRevista;
    private javax.swing.JTextField txtApellidoMa;
    private javax.swing.JTextField txtApellidoPa;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
