/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uam.pvoe.sw.formas;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.LinkedList;
import sun.java2d.pipe.RenderingEngine;
import uam.pvoe.atributos.Cliente;
import uam.pvoe.atributos.Editorial;
import uam.pvoe.atributos.Libros;
import uam.pvoe.atributos.Revistas;
import uam.pvoe.operaciones.RegistroCliente;
import uam.pvoe.operaciones.RegistroEditorial;
import uam.pvoe.operaciones.RegistroLibro;
import uam.pvoe.operaciones.RegistroPrestamosLibro;
import uam.pvoe.operaciones.RegistroRevista;
import uam.pvoe.operaciones.RegistrosPrestamosRevista;

/**
 *
 * @author Guerrero Cangas Sebastian
 * proyecto final 
 */
public class FrLibroPrestamo extends javax.swing.JFrame {

    /**
     * Creates new form FrPrestamo
     */
    public FrLibroPrestamo() {
        initComponents();
        llenarListaCliente();
        llenarListaLibros();
        mensaje();
        /**
         * llamamos las funciones
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlRegistroPestrestamo = new javax.swing.JPanel();
        lblMosNom = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellidoP = new javax.swing.JLabel();
        lblApellidoM = new javax.swing.JLabel();
        lblCurp = new javax.swing.JLabel();
        lblMosCurp = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JToggleButton();
        lblLibro = new javax.swing.JLabel();
        lblListaLilbro = new javax.swing.JLabel();
        cmbLibro = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        lblListaNombre = new javax.swing.JLabel();
        cmbNomCli = new javax.swing.JComboBox<>();
        lblRegistroCliente = new javax.swing.JLabel();
        btnRegistrarCkiente = new javax.swing.JButton();
        lblCliNore = new javax.swing.JLabel();
        lblMosApeP = new javax.swing.JLabel();
        lblMosApeM = new javax.swing.JLabel();
        lblMosFecha = new javax.swing.JLabel();
        lblMosLibro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnlRegistroPestrestamo.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Registrar Prestamo"));

        lblNombre.setText("Nombre");

        lblApellidoP.setText("Apellido Paterno");

        lblApellidoM.setText("Apelldio Materno ");

        lblCurp.setText("Curp");

        lblFecha.setText("Fecha del dia de hoy ");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lblLibro.setText("Libro");

        lblListaLilbro.setText("Lista de Libros registrados ");

        cmbLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLibroActionPerformed(evt);
            }
        });

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        lblListaNombre.setText("Lista de Nombres de clientes ya registrados ");

        cmbNomCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNomCliActionPerformed(evt);
            }
        });

        lblRegistroCliente.setText("Nombre Ingresado");

        btnRegistrarCkiente.setText("Registrar Cliente");
        btnRegistrarCkiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarCkienteActionPerformed(evt);
            }
        });

        lblCliNore.setText("Por si el cliente no esta registrado");

        javax.swing.GroupLayout PnlRegistroPestrestamoLayout = new javax.swing.GroupLayout(PnlRegistroPestrestamo);
        PnlRegistroPestrestamo.setLayout(PnlRegistroPestrestamoLayout);
        PnlRegistroPestrestamoLayout.setHorizontalGroup(
            PnlRegistroPestrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlRegistroPestrestamoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(PnlRegistroPestrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlRegistroPestrestamoLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(PnlRegistroPestrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblApellidoP)
                            .addComponent(lblMosApeP))
                        .addGap(79, 79, 79)
                        .addGroup(PnlRegistroPestrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlRegistroPestrestamoLayout.createSequentialGroup()
                                .addComponent(lblMosApeM)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(PnlRegistroPestrestamoLayout.createSequentialGroup()
                                .addComponent(lblApellidoM)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(PnlRegistroPestrestamoLayout.createSequentialGroup()
                        .addGroup(PnlRegistroPestrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblRegistroCliente)
                            .addComponent(cmbNomCli, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblListaNombre)
                            .addComponent(lblMosNom)
                            .addGroup(PnlRegistroPestrestamoLayout.createSequentialGroup()
                                .addComponent(btnRegistrar)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiar)
                                .addGap(18, 18, 18)
                                .addComponent(btnMenu)
                                .addGap(107, 107, 107)
                                .addGroup(PnlRegistroPestrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCliNore)
                                    .addComponent(btnRegistrarCkiente)))
                            .addGroup(PnlRegistroPestrestamoLayout.createSequentialGroup()
                                .addGroup(PnlRegistroPestrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PnlRegistroPestrestamoLayout.createSequentialGroup()
                                        .addGroup(PnlRegistroPestrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCurp)
                                            .addComponent(lblLibro)
                                            .addComponent(lblMosCurp, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(29, 29, 29))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlRegistroPestrestamoLayout.createSequentialGroup()
                                        .addComponent(lblMosLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)))
                                .addGroup(PnlRegistroPestrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFecha)
                                    .addComponent(lblListaLilbro)
                                    .addComponent(lblMosFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 22, Short.MAX_VALUE))))
        );
        PnlRegistroPestrestamoLayout.setVerticalGroup(
            PnlRegistroPestrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlRegistroPestrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblListaNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbNomCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblRegistroCliente)
                .addGap(0, 0, 0)
                .addGroup(PnlRegistroPestrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidoM)
                    .addComponent(lblApellidoP)
                    .addComponent(lblNombre))
                .addGap(12, 12, 12)
                .addGroup(PnlRegistroPestrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMosNom)
                    .addComponent(lblMosApeP)
                    .addComponent(lblMosApeM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlRegistroPestrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurp)
                    .addComponent(lblFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlRegistroPestrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMosFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMosCurp, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnlRegistroPestrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblListaLilbro)
                    .addComponent(lblLibro))
                .addGap(17, 17, 17)
                .addGroup(PnlRegistroPestrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlRegistroPestrestamoLayout.createSequentialGroup()
                        .addComponent(cmbLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblMosLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCliNore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlRegistroPestrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarCkiente)
                    .addComponent(btnMenu)
                    .addComponent(btnLimpiar)
                    .addComponent(btnRegistrar))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PnlRegistroPestrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PnlRegistroPestrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarCkienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarCkienteActionPerformed
        // TODO add your handling code here:
        FrRegistrarcliente menu = new FrRegistrarcliente();
        this.dispose();
        menu.setVisible(true);
        /**
        * abrimos con esto el Registrarcliente
        * cerramos esto
        */
    }//GEN-LAST:event_btnRegistrarCkienteActionPerformed

    private void cmbNomCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNomCliActionPerformed
        // TODO add your handling code here:
        int indice=cmbNomCli.getSelectedIndex(); //Recupera el indice empezando desde cero
        Cliente opcion =(Cliente) cmbNomCli.getSelectedItem();/**
        * la lista que tiene de seleccion el combobox de clientes
        */
        RegistroCliente arc = new RegistroCliente();/**
        * convocamos la funciones de la clase
        * RegistroCliente
        */

        if(opcion.getNombre().compareTo("--Selecciona el cliente--")==0){
            //mantenemos las lbl limpia
            lblMosNom.setText("");
        }else{
            //le agregamoms el  nombre a la lbl
            lblMosNom.setText(opcion.getNombre());
        }
        if(opcion.getApellidoP().compareTo("--Selecciona el cliente--")==0){
            //mantenemos las lbl limpia
            lblMosApeP.setText("");
        }else{
            //le agregamoms el Apellido paterno a la lbl
            lblMosApeP.setText(opcion.getApellidoP());
        }
        if(opcion.getApellidoM().compareTo("--Selecciona el cliente--")==0){
            //mantenemos las lbl limpia
            lblMosApeM.setText("");
        }else{
            //le agregamoms el Apellido materno a la lbl
            lblMosApeM.setText(opcion.getApellidoM());
        }
        if(opcion.getCurp().compareTo("--Selecciona el cliente--")==0){
            //mantener la lbl limpia
            lblMosCurp.setText("");
        }else{
            //le agregamoms la curp a la lbl
            lblMosCurp.setText(opcion.getCurp());
        }
        if(opcion.getNombre().compareTo("--Selecciona el cliente--")!=0 &&
            opcion.getApellidoM().compareTo("--Selecciona el cliente--")!=0
            && opcion.getApellidoP().compareTo("--Selecciona el cliente--")!=0 &&
            opcion.getCurp().compareTo("--Selecciona el cliente--")!=0){
            cmbNomCli.removeAllItems();
            llenarListaCliente();
            /**
            * si es difirente se borra la caja de texto y vuelve cargar la lista
            */
        }
    }//GEN-LAST:event_cmbNomCliActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        FrMenu menu = new FrMenu();
        this.dispose();
        menu.setVisible(true);
        /**
        * abrimos con esto el menu
        * cerramos esto
        */
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        RegistroPrestamosLibro lil = new RegistroPrestamosLibro();

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");//formato estandar de fecha
        Calendar calendar = Calendar.getInstance();//llamamos fecha por calentario
        calendar.setTime(new Date());//la recbe
        int calendarTime = Calendar.DAY_OF_MONTH;
        int temp = calendar.get(calendarTime);//para tener el dia
        calendar.set(calendarTime, temp+30);//aumentar el tiempo de fecha de regreso
        Date newDate = calendar.getTime();

        String na1 = lblMosNom.getText();
        String na2 = lblMosApeP.getText();
        String na3 = lblMosApeM.getText();
        String na4 = lblMosCurp.getText();
        String na5 = lblMosFecha.getText();

        String fechaComoCadena = sdf.format(newDate);
        String na6 = lblMosLibro.getText();

        /**
        * recibe todo lo que hay en las cajas de texto
        * para poder mandarla al archivo
        */

        lil.llenadoLP(na1, na2, na3, na4, na6,na5,fechaComoCadena);

        limpiar();//limpiamos las cajas de texto
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void cmbLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLibroActionPerformed
        // TODO add your handling code here:
        int indice=cmbLibro.getSelectedIndex(); //Recupera el indice empezando desde cero
        Libros opcion =(Libros) cmbLibro.getSelectedItem();/**
        * la lista que tiene de seleccion el combobox de Libros
        * podra cambiar y se guardara en el elemento tipo Libros
        */
        RegistroRevista arc = new RegistroRevista();/**
        * convocamos la funciones de la clase
        * RegistroRevista
        */

        if(opcion.getTitulo().compareTo("--Selecciona el Libro--")==0){
            //mantenemos la caja de texto limpiar
            lblMosLibro.setText("");
        }else{//llenamos la caja de texto con el titulo
            lblMosLibro.setText(opcion.getTitulo());
        }
        if(opcion.getTitulo().compareTo("--Selecciona el Libro--")!=0){
            cmbLibro.removeAllItems();
            llenarListaLibros();
            /**
            * si es difirente se borra la caja de texto y vuelve cargar la lista
            */
        }
    }//GEN-LAST:event_cmbLibroActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();//limpiar las cajas de texto
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrLibroPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrLibroPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrLibroPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrLibroPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrLibroPrestamo().setVisible(true);
            }
        });
    }
    
    
    private void limpiar(){
        lblMosNom.setText("");
        lblMosApeP.setText("");
        lblMosApeM.setText("");
        lblMosCurp.setText("");
        lblMosLibro.setText("");
        /**
         * para poder limpiar las lbl de texto
         */
        
    }
    
    private void mensaje(){
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        String fechaComoCadena = sdf.format(new Date());
        lblMosFecha.setText(fechaComoCadena);    //para poder tener una fecha establecida  
        /**
         * para poder poner la fecha en lbl
         */
    }
    
    private void llenarListaCliente(){
        RegistroCliente cli=new RegistroCliente();/**
         * llamamos la clase RegistroCliente
         */
        
        LinkedList<Cliente> Lista=cli.listaCliente();/**
         * generamos una lista ligada de Cliente
         */
        for(int i=0; i<Lista.size(); i++){
            //Toma la informacion del toString para poner las etiquetas en la interfaz
            cmbNomCli.addItem(Lista.get(i));//se lo ingresamos como objetos, a combobox
        }
    }
    
    private void llenarListaLibros(){
        RegistroLibro cli=new RegistroLibro();/**
         * llamamos la clase RegistroLibro
         */
        
        LinkedList<Libros> Lista=cli.listaL();/**
         * generamos una lista ligada de Libros
         */
        for(int i=0; i<Lista.size(); i++){
            //Toma la informacion del toString para poner las etiquetas en la interfaz
            cmbLibro.addItem(Lista.get(i));//se lo ingresamos como objetos, a combobox
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlRegistroPestrestamo;
    private javax.swing.JToggleButton btnLimpiar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistrarCkiente;
    private javax.swing.JComboBox<Libros> cmbLibro;
    private javax.swing.JComboBox<Cliente> cmbNomCli;
    private javax.swing.JLabel lblApellidoM;
    private javax.swing.JLabel lblApellidoP;
    private javax.swing.JLabel lblCliNore;
    private javax.swing.JLabel lblCurp;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblLibro;
    private javax.swing.JLabel lblListaLilbro;
    private javax.swing.JLabel lblListaNombre;
    private javax.swing.JLabel lblMosApeM;
    private javax.swing.JLabel lblMosApeP;
    private javax.swing.JLabel lblMosCurp;
    private javax.swing.JLabel lblMosFecha;
    private javax.swing.JLabel lblMosLibro;
    private javax.swing.JLabel lblMosNom;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRegistroCliente;
    // End of variables declaration//GEN-END:variables
}
