/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uam.pvoe.sw.formas;

/**
 *
 * @author Guerrero Cangas Sebastian
 * proyecto final 
 */
public class FrMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrMenu
     */
    public FrMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMenu = new javax.swing.JLabel();
        btnInformacion = new javax.swing.JButton();
        btnRcliente = new javax.swing.JButton();
        btnLibro = new javax.swing.JButton();
        btnRevista = new javax.swing.JButton();
        txtConsultar = new javax.swing.JButton();
        txtInfoCliente = new javax.swing.JButton();
        lblInformacion = new javax.swing.JLabel();
        lblControlCliente = new javax.swing.JLabel();
        lblRegistrarL = new javax.swing.JLabel();
        lblConsultas = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lblRegistroPrestamo = new javax.swing.JLabel();
        btnPresRevistas = new javax.swing.JButton();
        btnPresLibro = new javax.swing.JButton();
        btnConsultasPrestamos = new javax.swing.JButton();
        btnEditorial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblMenu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMenu.setText("MENU");

        btnInformacion.setText("Informacion del provedor");
        btnInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformacionActionPerformed(evt);
            }
        });

        btnRcliente.setText("Registrar Cliente");
        btnRcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRclienteActionPerformed(evt);
            }
        });

        btnLibro.setText("Libro");
        btnLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibroActionPerformed(evt);
            }
        });

        btnRevista.setText("Revista");
        btnRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevistaActionPerformed(evt);
            }
        });

        txtConsultar.setText("Consultar Libro o Revista");
        txtConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultarActionPerformed(evt);
            }
        });

        txtInfoCliente.setText("Info Cliente");
        txtInfoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInfoClienteActionPerformed(evt);
            }
        });

        lblInformacion.setText("Informacion");

        lblControlCliente.setText("Control Cliente");

        lblRegistrarL.setText("Registrar");

        lblConsultas.setText("Consultas");

        lblCliente.setText("Cliente");

        lblRegistroPrestamo.setText("Registrar un prestamo ");

        btnPresRevistas.setText("Prestamo Revista");
        btnPresRevistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPresRevistasActionPerformed(evt);
            }
        });

        btnPresLibro.setText("Prestamo Libro");
        btnPresLibro.setActionCommand("Prestamo\n Libro");
        btnPresLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPresLibroActionPerformed(evt);
            }
        });

        btnConsultasPrestamos.setText("Consultar Prestamos");
        btnConsultasPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasPrestamosActionPerformed(evt);
            }
        });

        btnEditorial.setText("Editorial");
        btnEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditorialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCliente)
                    .addComponent(lblConsultas)
                    .addComponent(lblRegistrarL)
                    .addComponent(lblControlCliente)
                    .addComponent(lblInformacion)
                    .addComponent(lblRegistroPrestamo)
                    .addComponent(btnInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtInfoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConsultasPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPresLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPresRevistas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRcliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblMenu)
                .addGap(18, 18, 18)
                .addComponent(lblInformacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInformacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblControlCliente)
                .addGap(3, 3, 3)
                .addComponent(btnRcliente)
                .addGap(18, 18, 18)
                .addComponent(lblRegistrarL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLibro)
                    .addComponent(btnRevista)
                    .addComponent(btnEditorial))
                .addGap(14, 14, 14)
                .addComponent(lblConsultas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConsultar)
                .addGap(18, 18, 18)
                .addComponent(lblCliente)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInfoCliente)
                    .addComponent(btnConsultasPrestamos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRegistroPrestamo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPresRevistas)
                    .addComponent(btnPresLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        btnPresLibro.getAccessibleContext().setAccessibleName("Prestamo\n Libro");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRclienteActionPerformed
        // TODO add your handling code here:
        FrRegistrarcliente cli = new FrRegistrarcliente();
        this.dispose();
        cli.setVisible(true);
        /**
         * llamamo la clase Registrarcliente
         * y cerramos esta
         */
    }//GEN-LAST:event_btnRclienteActionPerformed

    private void btnLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibroActionPerformed
        // TODO add your handling code here:
        FrRegistrarLibro ReL = new FrRegistrarLibro();
        this.dispose();
        ReL.setVisible(true);
        /**
         * llamamo la clase RegistrarLibro
         * y cerramos esta
         */
    }//GEN-LAST:event_btnLibroActionPerformed

    private void btnRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevistaActionPerformed
        // TODO add your handling code here:
        FrRegistrosRevista rev = new FrRegistrosRevista();
        this.dispose();
        rev.setVisible(true);
        /**
         * llamamo la clase RegistrosRevista
         * y cerramos esta
         */
    }//GEN-LAST:event_btnRevistaActionPerformed

    private void btnInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformacionActionPerformed
        // TODO add your handling code here:
        FrInformacion info = new FrInformacion();
        this.dispose();
        info.setVisible(true);
        /**
         * llamamo la clase Informacion
         * y cerramos esta
         */
    }//GEN-LAST:event_btnInformacionActionPerformed

    private void txtConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultarActionPerformed
        // TODO add your handling code here:
        FrConsultas con = new FrConsultas();
        this.dispose();
        con.setVisible(true);
        /**
         * llamamo la clase Consultas
         * y cerramos esta
         */
    }//GEN-LAST:event_txtConsultarActionPerformed

    private void txtInfoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInfoClienteActionPerformed
        // TODO add your handling code here:
        FrInformacionCliente cli = new FrInformacionCliente();
        this.dispose();
        cli.setVisible(true);
        /**
         * llamamo la clase InformacionCliente
         * y cerramos esta
         */
    }//GEN-LAST:event_txtInfoClienteActionPerformed

    private void btnPresLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPresLibroActionPerformed
        // TODO add your handling code here:
        FrLibroPrestamo seg = new FrLibroPrestamo();
        this.dispose();
        seg.setVisible(true);
        /**
         * llamamo la clase LibroPrestamo
         * y cerramos esta
         */
    }//GEN-LAST:event_btnPresLibroActionPerformed

    private void btnPresRevistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPresRevistasActionPerformed
        // TODO add your handling code here:
        FrRevistaPrestamo seg = new FrRevistaPrestamo();
        this.dispose();
        seg.setVisible(true);
        /**
         * llamamo la clase RevistaPrestamo
         * y cerramos esta
         */
    }//GEN-LAST:event_btnPresRevistasActionPerformed

    private void btnConsultasPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasPrestamosActionPerformed
        // TODO add your handling code here:
        FrConsultasPrestamos pres = new FrConsultasPrestamos();
        this.dispose();
        pres.setVisible(true);
        /**
         * llamamo la clase ConsultasPrestamos
         * y cerramos esta
         */
    }//GEN-LAST:event_btnConsultasPrestamosActionPerformed

    private void btnEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditorialActionPerformed
        // TODO add your handling code here:
         FrRegistrarEditorial edi = new FrRegistrarEditorial();
        this.dispose();
        edi.setVisible(true);
        /**
         * llamamos la pestaña del registro editorial
         */
    }//GEN-LAST:event_btnEditorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultasPrestamos;
    private javax.swing.JButton btnEditorial;
    private javax.swing.JButton btnInformacion;
    private javax.swing.JButton btnLibro;
    private javax.swing.JButton btnPresLibro;
    private javax.swing.JButton btnPresRevistas;
    private javax.swing.JButton btnRcliente;
    private javax.swing.JButton btnRevista;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblConsultas;
    private javax.swing.JLabel lblControlCliente;
    private javax.swing.JLabel lblInformacion;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblRegistrarL;
    private javax.swing.JLabel lblRegistroPrestamo;
    private javax.swing.JButton txtConsultar;
    private javax.swing.JButton txtInfoCliente;
    // End of variables declaration//GEN-END:variables
}
