/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uam.pvoe.sw.formas;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.JTextField;
import uam.pvoe.atributos.Editorial;
import uam.pvoe.operaciones.RegistroCliente;
import uam.pvoe.operaciones.RegistroRevista;

/**
 *
 * @author Guerrero Cangas Sebastian
 * proyecto final
 */
public class FrRegistrarcliente extends javax.swing.JFrame {

    /**
     * Creates new form FrRegistrarcliente
     */
    public FrRegistrarcliente() {
        initComponents();
        agruparSelecciones();
        mensaje();
        numeros();
        /**
         * llamamos la funciones
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgGenero = new javax.swing.ButtonGroup();
        pnlRegistros = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtApellidoP = new javax.swing.JTextField();
        txtApellidoM = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblApellidoP = new javax.swing.JLabel();
        lblApellidoM = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        txtCorreoE = new javax.swing.JTextField();
        lblGenero = new javax.swing.JLabel();
        rbHombre = new javax.swing.JRadioButton();
        rbNoquiero = new javax.swing.JRadioButton();
        lblCurp = new javax.swing.JLabel();
        txtCurp = new javax.swing.JTextField();
        rbMujer = new javax.swing.JRadioButton();
        lblCorreoE = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        btnlimpiarR = new javax.swing.JButton();
        pnlGustos = new javax.swing.JPanel();
        lblTipos = new javax.swing.JLabel();
        cbCienciaF = new javax.swing.JCheckBox();
        cbFantasia = new javax.swing.JCheckBox();
        cbClasicos = new javax.swing.JCheckBox();
        cbRomance = new javax.swing.JCheckBox();
        cbTerroryMis = new javax.swing.JCheckBox();
        btnLimpiarG = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlRegistros.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Registro"));

        lblNombre.setText("Nombre ");

        lblApellidoP.setText("Apellido Paterno");

        lblApellidoM.setText("Apellido Materno");

        lblDireccion.setText("Direccion");

        lblNumero.setText("Numero Telefonico");

        lblGenero.setText("Genero");

        rbHombre.setText("Hombre");

        rbNoquiero.setText("No quiero decir");

        lblCurp.setText("CURP");

        txtCurp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCurpKeyTyped(evt);
            }
        });

        rbMujer.setText("Mujer");

        lblCorreoE.setText("Correo electronico");

        txtNumero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNumeroMouseClicked(evt);
            }
        });

        btnlimpiarR.setText("Limpia datos");
        btnlimpiarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegistrosLayout = new javax.swing.GroupLayout(pnlRegistros);
        pnlRegistros.setLayout(pnlRegistrosLayout);
        pnlRegistrosLayout.setHorizontalGroup(
            pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                        .addComponent(lblNombre)
                        .addComponent(lblCurp)
                        .addComponent(txtCurp))
                    .addComponent(lblGenero)
                    .addGroup(pnlRegistrosLayout.createSequentialGroup()
                        .addComponent(rbHombre)
                        .addGap(18, 18, 18)
                        .addComponent(rbMujer))
                    .addComponent(rbNoquiero))
                .addGap(29, 29, 29)
                .addGroup(pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistrosLayout.createSequentialGroup()
                        .addComponent(lblApellidoP)
                        .addGap(58, 58, 58)
                        .addComponent(lblApellidoM))
                    .addGroup(pnlRegistrosLayout.createSequentialGroup()
                        .addGroup(pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCorreoE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDireccion)))
                    .addComponent(lblNumero)
                    .addGroup(pnlRegistrosLayout.createSequentialGroup()
                        .addGroup(pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCorreoE, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(txtNumero))
                        .addGap(18, 18, 18)
                        .addGroup(pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnlimpiarR)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        pnlRegistrosLayout.setVerticalGroup(
            pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrosLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblApellidoP)
                    .addComponent(lblApellidoM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDireccion)
                        .addComponent(lblCorreoE))
                    .addGroup(pnlRegistrosLayout.createSequentialGroup()
                        .addComponent(lblCurp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCurp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCorreoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistrosLayout.createSequentialGroup()
                        .addComponent(lblGenero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbHombre)
                            .addComponent(rbMujer))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbNoquiero))
                    .addGroup(pnlRegistrosLayout.createSequentialGroup()
                        .addComponent(lblNumero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnlimpiarR))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pnlGustos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Gustos\n"));

        lblTipos.setText("Tipos de genero");

        cbCienciaF.setText("Ciencia Ficción");

        cbFantasia.setText("Fantasía");

        cbClasicos.setText("Clásicos");

        cbRomance.setText("Romance");

        cbTerroryMis.setText("Terror y Misterio");

        btnLimpiarG.setText("Limpiar G");
        btnLimpiarG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGustosLayout = new javax.swing.GroupLayout(pnlGustos);
        pnlGustos.setLayout(pnlGustosLayout);
        pnlGustosLayout.setHorizontalGroup(
            pnlGustosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGustosLayout.createSequentialGroup()
                .addComponent(lblTipos)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlGustosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGustosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbCienciaF)
                    .addComponent(cbTerroryMis))
                .addGap(18, 18, 18)
                .addGroup(pnlGustosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbFantasia)
                    .addComponent(cbRomance))
                .addGroup(pnlGustosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGustosLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(cbClasicos))
                    .addGroup(pnlGustosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpiarG)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlGustosLayout.setVerticalGroup(
            pnlGustosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGustosLayout.createSequentialGroup()
                .addComponent(lblTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlGustosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbFantasia)
                    .addComponent(cbTerroryMis)
                    .addComponent(cbClasicos))
                .addGap(18, 18, 18)
                .addGroup(pnlGustosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCienciaF)
                    .addComponent(cbRomance)
                    .addComponent(btnLimpiarG))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlGustos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRegistrar)
                                .addGap(30, 30, 30)
                                .addComponent(btnLimpiar))
                            .addComponent(btnMenu)))
                    .addComponent(pnlRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegistrar)
                            .addComponent(btnLimpiar))
                        .addGap(27, 27, 27)
                        .addComponent(btnMenu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(pnlGustos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void num(JTextField a){//para solo poder registrar numeros
        a.addKeyListener(new KeyAdapter(){
            public void keyTyped(KeyEvent e){
                char c = e.getKeyChar();
                if(!Character.isDigit(c) && c != '.'){
                    e.consume();
                }else if(c== '.' && txtNumero.getText().contains(".")){
                    e.consume();
                }
            }
        });
    }
    
    private void numeros(){
        num(txtNumero);//llamamos la funcion con la caja de texto
    }
    
    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        FrMenu menu = new FrMenu();
        this.dispose();
        menu.setVisible(true);
        /**
         * abrimos el menu
         * y lo cerramos
         */
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnlimpiarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarRActionPerformed
        // TODO add your handling code here:
        limpiar();
        mensaje();
        limpiarRb();
        /**
         * para poder limpiar
         */
    }//GEN-LAST:event_btnlimpiarRActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        RegistroCliente cli = new RegistroCliente();
        
        String p="";
        String p2="";
        String p3="";
        String p4="";
        String p5="";
        int gus=0;
        
        String na = txtNombre.getText();
        String na2 = txtApellidoP.getText();
        String na3 = txtApellidoM.getText();
        String na4 = txtCurp.getText().toUpperCase();
        String na5 = txtCorreoE.getText();
        String na6 = txtDireccion.getText();
        
        long num = Long.parseLong(txtNumero.getText());
        
        if(rbHombre.isSelected()==true){//si esta activado mandara ese mensaje
            String na7= "Hombre";
            ArrayList<String> gustos = new ArrayList<String>();
            
            if(cbCienciaF.isSelected()==true){
                 p = "Ciencia Ficcion";
                 gustos.add(p);
            
            }
            if(cbClasicos.isSelected()==true){
                p2 = "Clasico";
                gustos.add(p2);
            }
            if(cbFantasia.isSelected()==true){
                p3 = "fantasia";
                gustos.add(p3);
            }
            if(cbRomance.isSelected()==true){
                p4 = "Romance";
                gustos.add(p4);
            }
            if(cbTerroryMis.isSelected()==true){
                p5 = "terror y misterio";
                gustos.add(p5);
            }
            String p6="";
            gus=gustos.size();
            if(gus==1){//para poder ir identificando el gusto
                for(int i=0; i<gustos.size(); i++){
                    p6=gustos.get(0);
                    System.out.print(gustos.get(i));
                }
            }else if(gus==2){//para poder ir identificando el gusto
                for(int i=0; i<gustos.size(); i++){
                    p6=gustos.get(0)+","+gustos.get(1);
                    System.out.print(gustos.get(i));
                }
            }else if(gus==3){//para poder ir identificando el gusto
                for(int i=0; i<gustos.size(); i++){
                    p6=gustos.get(0)+","+gustos.get(1)+","+gustos.get(2);
                    System.out.print(gustos.get(i));
                }
            }else if(gus==4){//para poder ir identificando el gusto
                for(int i=0; i<gustos.size(); i++){
                    p6=gustos.get(0)+","+gustos.get(1)+","+gustos.get(2)+gustos.get(3);
                    System.out.print(gustos.get(i));
                }
            }else if(gus==5){//para poder ir identificando el gusto
                for(int i=0; i<gustos.size(); i++){
                    p6=gustos.get(0)+","+gustos.get(1)+","+gustos.get(2)+gustos.get(3)+gustos.get(4);
                    System.out.print(gustos.get(i));
                }
            }
            
            cli.llenadoC(na, na2, na3, na4, na5, na6, num, na7, p6);// lo mandamos ala funcion
        }else if(rbMujer.isSelected()==true){//si esta activado mandara ese mensaje
            String na7="mujer";
            ArrayList<String> gustos = new ArrayList<String>();
            if(cbCienciaF.isSelected()==true){
                 p = "Ciencia Ficcion";
                 gustos.add(p);

            }
            if(cbClasicos.isSelected()==true){
                p2 = "Clasico";
                gustos.add(p2);
            }
            if(cbFantasia.isSelected()==true){
                p3 = "fantasia";
                gustos.add(p3);
            }
            if(cbRomance.isSelected()==true){
                p4 = "Romance";
                gustos.add(p4);
            }
            if(cbTerroryMis.isSelected()==true){
                p5 = "terror y misterio";
                gustos.add(p5);
            }
            String p6="";
            gus=gustos.size();
            if(gus==1){//para poder ir identificando el gusto
                for(int i=0; i<gustos.size(); i++){
                    p6=gustos.get(0);
                    System.out.print(gustos.get(i));
                }
            }else if(gus==2){//para poder ir identificando el gusto
                for(int i=0; i<gustos.size(); i++){
                    p6=gustos.get(0)+","+gustos.get(1);
                    System.out.print(gustos.get(i));
                }
            }else if(gus==3){//para poder ir identificando el gusto
                for(int i=0; i<gustos.size(); i++){
                    p6=gustos.get(0)+","+gustos.get(1)+","+gustos.get(2);
                    System.out.print(gustos.get(i));
                }
            }else if(gus==4){//para poder ir identificando el gusto
                for(int i=0; i<gustos.size(); i++){
                    p6=gustos.get(0)+","+gustos.get(1)+","+gustos.get(2)+gustos.get(3);
                    System.out.print(gustos.get(i));
                }
            }else if(gus==5){//para poder ir identificando el gusto
                for(int i=0; i<gustos.size(); i++){
                    p6=gustos.get(0)+","+gustos.get(1)+","+gustos.get(2)+gustos.get(3)+gustos.get(4);
                    System.out.print(gustos.get(i));
                }
            }
            cli.llenadoC(na, na2, na3, na4, na5, na6, num, na7, p6);//lo mandamos a clase
        }else if(rbNoquiero.isSelected()==true){
            String na7="no quiero decir";
            ArrayList<String> gustos = new ArrayList<String>();
            if(cbCienciaF.isSelected()==true){
                 p = "Ciencia Ficcion";
                 gustos.add(p);

            }
            if(cbClasicos.isSelected()==true){
                p2 = "Clasico";
                gustos.add(p2);
            }
            if(cbFantasia.isSelected()==true){
                p3 = "fantasia";
                gustos.add(p3);
            }
            if(cbRomance.isSelected()==true){
                p4 = "Romance";
                gustos.add(p4);
            }
            if(cbTerroryMis.isSelected()==true){
                p5 = "terror y misterio";
                gustos.add(p5);
            }
            String p6="";
            gus=gustos.size();
            if(gus==1){//para poder ir identificando el gusto
                for(int i=0; i<gustos.size(); i++){
                    p6=gustos.get(0);
                    System.out.print(gustos.get(i));
                }
            }else if(gus==2){//para poder ir identificando el gusto
                for(int i=0; i<gustos.size(); i++){
                    p6=gustos.get(0)+","+gustos.get(1);
                    System.out.print(gustos.get(i));
                }
            }else if(gus==3){//para poder ir identificando el gusto
                for(int i=0; i<gustos.size(); i++){
                    p6=gustos.get(0)+","+gustos.get(1)+","+gustos.get(2);
                    System.out.print(gustos.get(i));
                }
            }else if(gus==4){//para poder ir identificando el gusto
                for(int i=0; i<gustos.size(); i++){
                    p6=gustos.get(0)+","+gustos.get(1)+","+gustos.get(2)+gustos.get(3);
                    System.out.print(gustos.get(i));
                }
            }else if(gus==5){//para poder ir identificando el gusto
                for(int i=0; i<gustos.size(); i++){
                    p6=gustos.get(0)+","+gustos.get(1)+","+gustos.get(2)+gustos.get(3)+gustos.get(4);
                    System.out.print(gustos.get(i));
                }
            }
            cli.llenadoC(na, na2, na3, na4, na5, na6, num, na7, p6);//lo mandamos a clase
        }
        
        limpiar();
        LselecionG();
        limpiarRb();
        mensaje();
        /**
         * llamamos las funciones
         */
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtNumeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNumeroMouseClicked
        // TODO add your handling code here:
        String p = txtNumero.getText();
        if(p.compareTo("solo numeros >:c")==0){
            txtNumero.setText("");
        }
        
        /**
         * cuando salga en caja de texto ese mensaje 
         * al darle click se borrar
         */
    }//GEN-LAST:event_txtNumeroMouseClicked

    private void btnLimpiarGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarGActionPerformed
        // TODO add your handling code here:
        LselecionG();
        /**
         * para poder limpiar los gustos
         */
    }//GEN-LAST:event_btnLimpiarGActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        LselecionG();
        limpiar();
        limpiarRb();
        mensaje();
        /**
         * para poder limpiar
         */
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtCurpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCurpKeyTyped
        // TODO add your handling code here:
        char caracter=evt.getKeyChar();
        if(Character.isLowerCase(caracter)){
            evt.setKeyChar(Character.toUpperCase(caracter));
        }
        /**
         * para pasarlo a letras mayusculas
         */
    }//GEN-LAST:event_txtCurpKeyTyped

    public void LselecionG(){
        
        cbCienciaF.setSelected(false);
        cbClasicos.setSelected(false);
        cbFantasia.setSelected(false);
        cbRomance.setSelected(false);
        cbTerroryMis.setSelected(false);
        /**
         * para que ninguno este activado
         */
        
    }
    
    public void limpiarRb(){
        btgGenero.clearSelection();//limpiar los radio boton
    }
    
    public void limpiar(){
        txtNombre.setText("");
        txtApellidoP.setText("");
        txtApellidoM.setText("");
        txtCorreoE.setText("");
        txtDireccion.setText("");
        txtNumero.setText("");
        txtCurp.setText("");
        /**
         * para poder limpiar la cajas de texto
         */
    }
    
    public void agruparSelecciones(){
        btgGenero.add(rbHombre);
        btgGenero.add(rbMujer);
        btgGenero.add(rbNoquiero);
        
        /**
         * para hacerlos mutuamente excluyentes
         */
    }
    
     public void mensaje(){
        txtNumero.setText("solo numeros >:c");//mensaje solo para dar una idea 
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrRegistrarcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrRegistrarcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrRegistrarcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrRegistrarcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrRegistrarcliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgGenero;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLimpiarG;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnlimpiarR;
    private javax.swing.JCheckBox cbCienciaF;
    private javax.swing.JCheckBox cbClasicos;
    private javax.swing.JCheckBox cbFantasia;
    private javax.swing.JCheckBox cbRomance;
    private javax.swing.JCheckBox cbTerroryMis;
    private javax.swing.JLabel lblApellidoM;
    private javax.swing.JLabel lblApellidoP;
    private javax.swing.JLabel lblCorreoE;
    private javax.swing.JLabel lblCurp;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblTipos;
    private javax.swing.JPanel pnlGustos;
    private javax.swing.JPanel pnlRegistros;
    private javax.swing.JRadioButton rbHombre;
    private javax.swing.JRadioButton rbMujer;
    private javax.swing.JRadioButton rbNoquiero;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtCorreoE;
    private javax.swing.JTextField txtCurp;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
