/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uam.pvoe.sw.formas;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.LinkedList;
import javax.swing.JTextField;
import uam.pvoe.atributos.Editorial;
import uam.pvoe.operaciones.RegistroEditorial;
import uam.pvoe.operaciones.RegistroLibro;

/**
 *
 * @author Guerrero Cangas Sebastian
 * proyecto final
 */
public class FrRegistrarLibro extends javax.swing.JFrame {

    /**
     * Creates new form FrRegistrarLibro
     */
    public FrRegistrarLibro() {
        initComponents();
        mensaje();
        numeros();
        llenarListaEditorial();
    }
    
    
    private void num(JTextField a){//para poder limitar la escritura a numero la caja de texto
        a.addKeyListener(new KeyAdapter(){
            public void keyTyped(KeyEvent e){
                char c = e.getKeyChar();
                if(!Character.isDigit(c) && c != '.'){
                    e.consume();
                }else if(c== '.' && txtCantidad.getText().contains(".")){
                    e.consume();
                }else if(c== '.' && txtIsbn.getText().contains("-")){
                    e.consume();
                }
            }
        });
    }
    
    private void numeros(){
        num(txtCantidad);
        num(txtIsbn);
        /**
         * mandamos la caja de texto a la funcion
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnRegistrosLibro = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        lblListaE = new javax.swing.JLabel();
        cmbEditorial = new javax.swing.JComboBox<>();
        lblTitulo = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        lblEditorial = new javax.swing.JLabel();
        lblMosedi = new javax.swing.JLabel();
        lblIsbn = new javax.swing.JLabel();
        txtIsbn = new javax.swing.JTextField();
        lblCantidad = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnRegistrosLibro.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Registro Libro\n"));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        lblListaE.setText("Lista de las editoriales");

        cmbEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEditorialActionPerformed(evt);
            }
        });

        lblTitulo.setText("Titulo");

        lblEditorial.setText("Editorial");

        lblIsbn.setText("ISBN");

        txtIsbn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIsbnMouseClicked(evt);
            }
        });
        txtIsbn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIsbnKeyTyped(evt);
            }
        });

        lblCantidad.setText("Cantidad");

        txtCantidad.setSelectionColor(new java.awt.Color(102, 255, 102));
        txtCantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCantidadMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnRegistrosLibroLayout = new javax.swing.GroupLayout(pnRegistrosLibro);
        pnRegistrosLibro.setLayout(pnRegistrosLibroLayout);
        pnRegistrosLibroLayout.setHorizontalGroup(
            pnRegistrosLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRegistrosLibroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnRegistrosLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCantidad)
                    .addGroup(pnRegistrosLibroLayout.createSequentialGroup()
                        .addGroup(pnRegistrosLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnRegistrosLibroLayout.createSequentialGroup()
                                .addComponent(btnLimpiar)
                                .addGap(18, 18, 18)
                                .addComponent(btnMenu))
                            .addGroup(pnRegistrosLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblMosedi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblEditorial, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(34, 34, 34)
                        .addGroup(pnRegistrosLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegistrar)
                            .addGroup(pnRegistrosLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbEditorial, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtIsbn)
                                .addGroup(pnRegistrosLibroLayout.createSequentialGroup()
                                    .addGroup(pnRegistrosLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblIsbn)
                                        .addComponent(lblListaE))
                                    .addGap(0, 63, Short.MAX_VALUE))))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        pnRegistrosLibroLayout.setVerticalGroup(
            pnRegistrosLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRegistrosLibroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnRegistrosLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(lblIsbn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnRegistrosLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnRegistrosLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEditorial)
                    .addComponent(lblListaE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnRegistrosLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMosedi))
                .addGap(26, 26, 26)
                .addComponent(lblCantidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(pnRegistrosLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnMenu)
                    .addComponent(btnRegistrar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(pnRegistrosLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnRegistrosLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        RegistroLibro lol = new RegistroLibro();
        
        
        String na= txtTitulo.getText();
        long na2=Long.parseLong(txtIsbn.getText());
        String na3=lblMosedi.getText();
        int p = Integer.parseInt(txtCantidad.getText());
        
        /**
         * mandamos la informacion de la caja de texto a sus respectivas
         * variables y de ahi la mandamos a las funcion
         */
        
        lol.llenadoL(na, na2, na3, p);
        
        limpiar();//limpiamos la caja de texto
        mensaje();//llamamos el mensaje
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        FrMenu menu = new FrMenu();
        this.dispose();
        menu.setVisible(true);
        /**
         * llamamos la venta del menu 
         * y cerramos esta
         */
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();//limpiamos la caja de texto
        mensaje();//llamamos los mensajes
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtCantidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCantidadMouseClicked
        // TODO add your handling code here:
        String p = txtCantidad.getText();
        if(p.compareTo("solo numeros >:c")==0){
            txtCantidad.setText("");
        }
        /**
         * cuando salga en caja de texto ese mensaje 
         * al darle click se borrar
         */
    }//GEN-LAST:event_txtCantidadMouseClicked

    private void cmbEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEditorialActionPerformed
        // TODO add your handling code here:
        
        int indice=cmbEditorial.getSelectedIndex(); //Recupera el indice empezando desde cero
        Editorial opcion =(Editorial) cmbEditorial.getSelectedItem();/**
         * la lista que tiene de seleccion el combobox de Editorial
         * podra cambiar y se guardara en el elemento 
         */  
        RegistroEditorial arc = new RegistroEditorial();/**
         * convocamos la funciones de la clase
         * RegistroEditorial
         */
        
        if(opcion.getNombreE().compareTo("--Selecciona el editorial--")==0){//limpiamos caja de texto
            lblMosedi.setText("");
        }else{
            lblMosedi.setText(opcion.getNombreE());
        }
        if(opcion.getNombreE().compareTo("--Selecciona el editorial--")!=0){
            cmbEditorial.removeAllItems();
            llenarListaEditorial();
            /**
             * si es difirente se borra la caja de texto y vuelve cargar la lista
             */
        }
        
    }//GEN-LAST:event_cmbEditorialActionPerformed

    private void txtIsbnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIsbnMouseClicked
        // TODO add your handling code here:
        String p = txtIsbn.getText();
        if(p.compareTo("solo numeros >:c")==0){
            txtIsbn.setText("");
        }
        /**
         * cuando salga en caja de texto ese mensaje 
         * al darle click se borrar
         */
    }//GEN-LAST:event_txtIsbnMouseClicked

    private void txtIsbnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIsbnKeyTyped
        // TODO add your handling code here:
        if(txtIsbn.getText().length() >= 13){
            evt.consume();
        }
        /**
         * limitamos la cantidad de caracteres para la 
         * caja de texto
         */
    }//GEN-LAST:event_txtIsbnKeyTyped

    public void limpiar(){
        txtCantidad.setText("");
        lblMosedi.setText("");
        txtIsbn.setText("");
        txtTitulo.setText("");
        /**
         * usado parra limpiar las cajas de texto
         */
    }
    
    public void mensaje(){
        txtCantidad.setText("solo numeros >:c");
        txtIsbn.setText("solo numeros >:c");
        /**
         * los mensajes que se iran a la caja de texto
         */
    }
    
    
    public void llenarListaEditorial(){
        RegistroEditorial edi=new RegistroEditorial();/**
         * llamamos la clase RegistroEditorial
         */
        
        LinkedList<Editorial> Lista=edi.listaEditorial();/**
         * generamos una lista ligada de editoriales, que le agregara la lista
         * de la clase 
         */
        for(int i=0; i<Lista.size(); i++){
            //Toma la informacion del toString para poner las etiquetas en la interfaz
            cmbEditorial.addItem(Lista.get(i));//se lo ingresamos como objetos, a combobox
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrRegistrarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrRegistrarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrRegistrarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrRegistrarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrRegistrarLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<Editorial> cmbEditorial;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblEditorial;
    private javax.swing.JLabel lblIsbn;
    private javax.swing.JLabel lblListaE;
    private javax.swing.JLabel lblMosedi;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnRegistrosLibro;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtIsbn;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
