/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uam.pvoe.sw.formas;

import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import java.util.LinkedList;
import sun.java2d.pipe.RenderingEngine;
import uam.pvoe.atributos.Cliente;
import uam.pvoe.atributos.Editorial;
import uam.pvoe.atributos.Revistas;
import uam.pvoe.operaciones.RegistroCliente;
import uam.pvoe.operaciones.RegistroEditorial;
import uam.pvoe.operaciones.RegistroRevista;
import uam.pvoe.operaciones.RegistrosPrestamosRevista;

/**
 *
 * @author Guerrero Cangas Sebastian
 * proyecto final
 */
public class FrRevistaPrestamo extends javax.swing.JFrame {

    /**
     * Creates new form FrPrestamo
     */
    public FrRevistaPrestamo() {
        initComponents();
        llenarListaCliente();
        llenarListaRevista();
        mensaje();
        /**
         * llamamos las funciones
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlRegistroPestrestamo = new javax.swing.JPanel();
        lblMosNom = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellidoP = new javax.swing.JLabel();
        lblApellidoM = new javax.swing.JLabel();
        lblCurp = new javax.swing.JLabel();
        lblMosCurp = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblMosFecha = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JToggleButton();
        lblIngresarRev = new javax.swing.JLabel();
        lblListaRev = new javax.swing.JLabel();
        lblMosRev = new javax.swing.JLabel();
        cmbListaR = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        lblListaNombre = new javax.swing.JLabel();
        cmbNomCli = new javax.swing.JComboBox<>();
        lblRegistroCliente = new javax.swing.JLabel();
        btnRegistrarCkiente = new javax.swing.JButton();
        lblClinoRe = new javax.swing.JLabel();
        lblMosApeP = new javax.swing.JLabel();
        lblMosApeM = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblMosNum = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PnlRegistroPestrestamo.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Registrar Prestamo"));

        lblNombre.setText("Nombre");

        lblApellidoP.setText("Apellido Paterno");

        lblApellidoM.setText("Apelldio Materno ");

        lblCurp.setText("Curp");

        lblFecha.setText("Fecha del dia de hoy ");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lblIngresarRev.setText("Revista  ");

        lblListaRev.setText("Lista de Revista registrados ");

        cmbListaR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbListaRActionPerformed(evt);
            }
        });

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        lblListaNombre.setText("Nombre de clientes ya registrados ");

        cmbNomCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNomCliActionPerformed(evt);
            }
        });

        lblRegistroCliente.setText("Nombre Ingresado");

        btnRegistrarCkiente.setText("Registrar Cliente");
        btnRegistrarCkiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarCkienteActionPerformed(evt);
            }
        });

        lblClinoRe.setText("Por si el cliente no esta registrado");

        lblNumero.setText("Numero de Revista");

        javax.swing.GroupLayout PnlRegistroPestrestamoLayout = new javax.swing.GroupLayout(PnlRegistroPestrestamo);
        PnlRegistroPestrestamo.setLayout(PnlRegistroPestrestamoLayout);
        PnlRegistroPestrestamoLayout.setHorizontalGroup(
            PnlRegistroPestrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlRegistroPestrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlRegistroPestrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addComponent(lblRegistroCliente)
                    .addComponent(cmbNomCli, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblListaNombre)
                    .addGroup(PnlRegistroPestrestamoLayout.createSequentialGroup()
                        .addComponent(btnRegistrar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar)
                        .addGap(18, 18, 18)
                        .addComponent(btnMenu)
                        .addGap(58, 58, 58)
                        .addGroup(PnlRegistroPestrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblClinoRe)
                            .addComponent(btnRegistrarCkiente)))
                    .addComponent(lblCurp)
                    .addComponent(lblMosCurp)
                    .addGroup(PnlRegistroPestrestamoLayout.createSequentialGroup()
                        .addGroup(PnlRegistroPestrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlRegistroPestrestamoLayout.createSequentialGroup()
                                .addGroup(PnlRegistroPestrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIngresarRev)
                                    .addComponent(lblMosRev, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(PnlRegistroPestrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMosApeP)
                                    .addComponent(lblApellidoP)
                                    .addComponent(lblFecha)
                                    .addComponent(lblMosFecha)
                                    .addComponent(lblMosNum)
                                    .addComponent(lblNumero)))
                            .addComponent(lblMosNom))
                        .addGap(55, 55, 55)
                        .addGroup(PnlRegistroPestrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblListaRev)
                            .addComponent(lblApellidoM)
                            .addComponent(cmbListaR, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMosApeM))))
                .addGap(0, 46, Short.MAX_VALUE))
        );
        PnlRegistroPestrestamoLayout.setVerticalGroup(
            PnlRegistroPestrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlRegistroPestrestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblListaNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbNomCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblRegistroCliente)
                .addGap(8, 8, 8)
                .addGroup(PnlRegistroPestrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidoM)
                    .addComponent(lblApellidoP)
                    .addComponent(lblNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlRegistroPestrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMosNom)
                    .addComponent(lblMosApeM)
                    .addComponent(lblMosApeP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlRegistroPestrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCurp)
                    .addComponent(lblFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlRegistroPestrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMosCurp)
                    .addComponent(lblMosFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlRegistroPestrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PnlRegistroPestrestamoLayout.createSequentialGroup()
                        .addComponent(lblIngresarRev)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMosRev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PnlRegistroPestrestamoLayout.createSequentialGroup()
                        .addGroup(PnlRegistroPestrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumero)
                            .addComponent(lblListaRev))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PnlRegistroPestrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMosNum)
                            .addComponent(cmbListaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 62, Short.MAX_VALUE)
                .addComponent(lblClinoRe)
                .addGap(3, 3, 3)
                .addGroup(PnlRegistroPestrestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarCkiente)
                    .addComponent(btnMenu)
                    .addComponent(btnLimpiar)
                    .addComponent(btnRegistrar))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(PnlRegistroPestrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PnlRegistroPestrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbNomCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNomCliActionPerformed
        // TODO add your handling code here:
        int indice=cmbNomCli.getSelectedIndex(); //Recupera el indice empezando desde cero
        Cliente opcion =(Cliente) cmbNomCli.getSelectedItem();/**
         * la lista que tiene de seleccion el combobox de Cliente
         * podra cambiar y se guardara en el elemento 
         */  
        RegistroCliente arc = new RegistroCliente();/**
         * convocamos la funciones de la clase
         * RegistroCliente
         */
        
        if(opcion.getNombre().compareTo("--Selecciona el cliente--")==0){
            //mantenemos las lbl limpia
            lblMosNom.setText("");
        }else{
            //le agregamoms el  nombre a la lbl
            lblMosNom.setText(opcion.getNombre());
        }
        if(opcion.getApellidoP().compareTo("--Selecciona el cliente--")==0){
            //mantenemos las lbl limpia
            lblMosApeP.setText("");
        }else{
            //le agregamoms el Apellido paterno a la lbl 
            lblMosApeP.setText(opcion.getApellidoP());
        }
        if(opcion.getApellidoM().compareTo("--Selecciona el cliente--")==0){
            //mantenemos las lbl limpia
            lblMosApeM.setText("");
        }else{
            //le agregamoms el Apellido materno a la lbl 
            lblMosApeM.setText(opcion.getApellidoM());
        }
        if(opcion.getCurp().compareTo("--Selecciona el cliente--")==0){
            //mantener la lbl limpia
            lblMosCurp.setText("");
        }else{
            //le agregamoms la curp a la lbl 
            lblMosCurp.setText(opcion.getCurp());
        }
        if(opcion.getNombre().compareTo("--Selecciona el cliente--")!=0 && 
                opcion.getApellidoM().compareTo("--Selecciona el cliente--")!=0
                && opcion.getApellidoP().compareTo("--Selecciona el cliente--")!=0 &&
                opcion.getCurp().compareTo("--Selecciona el cliente--")!=0){
            cmbNomCli.removeAllItems();
            llenarListaCliente();
            /**
             * si es difirente se borra la caja de texto y vuelve cargar la lista
             */
        }
        
    }//GEN-LAST:event_cmbNomCliActionPerformed

    private void cmbListaRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbListaRActionPerformed
        // TODO add your handling code here:
        int indice=cmbListaR.getSelectedIndex(); //Recupera el indice empezando desde cero
        Revistas opcion =(Revistas) cmbListaR.getSelectedItem();/**
         * la lista que tiene de seleccion el combobox de Revistas
         * podra cambiar y se guardara en el elemento
         */  
        RegistroRevista arc = new RegistroRevista();/**
         * convocamos la funciones de la clase
         * RegistroRevista
         */
        
        if(opcion.getTitulo().compareTo("--Selecciona la revista--   ")==0){
            //para poder mantener limpia la lbl
            lblMosNum.setText("");
            lblMosRev.setText("");
        }else{
            //agregamos e lnumero y titulo a la lbl
            lblMosRev.setText(opcion.getTitulo());
             String str = Long.toString(opcion.getNumero());
             lblMosNum.setText(str);
        }
           
        if(opcion.getTitulo().compareTo("--Selecciona la revista--   ")!=0
                && opcion.getNumero()!=0){
            cmbListaR.removeAllItems();
            llenarListaRevista();
            /**
             * si es difirente se borra la caja de texto y vuelve cargar la lista
             */
        }
    }//GEN-LAST:event_cmbListaRActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        RegistrosPrestamosRevista rev = new RegistrosPrestamosRevista();
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");//formato estandar de fecha
        Calendar calendar = Calendar.getInstance();//llamamos fecha por calentario
        calendar.setTime(new Date());//la recbe
        int calendarTime = Calendar.DAY_OF_MONTH;
        int temp = calendar.get(calendarTime);//para tener el dia
        calendar.set(calendarTime, temp+30);//aumentar el tiempo de fecha de regreso
        Date newDate = calendar.getTime();
       
        String na1 = lblMosNom.getText();
        String na2 = lblMosApeP.getText();
        String na3 = lblMosApeM.getText();
        String na4 = lblMosCurp.getText();
        String na5 = lblMosFecha.getText();
        String na6 = lblMosRev.getText();
        
        String fechaComoCadena = sdf.format(newDate);
        long p = Long.parseLong(lblMosNum.getText());
        
        /**
         * recibe todo lo que hay en las cajas de texto 
         * para poder mandarla al archivo
         */
        rev.llenadoRP(na1, na2, na3, na4, na6,p,na5,fechaComoCadena);
        
        
        limpiar();//limpiamos las cajas de texto
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        FrMenu menu = new FrMenu();
        this.dispose();
        menu.setVisible(true);
        /**
         * abrimos con esto el menu
         * cerramos esto
         */
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnRegistrarCkienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarCkienteActionPerformed
        // TODO add your handling code here:
        FrRegistrarcliente menu = new FrRegistrarcliente();
        this.dispose();
        menu.setVisible(true);
        /**
         * abrimos con esto el Registrarcliente
         * cerramos esto
         */
    }//GEN-LAST:event_btnRegistrarCkienteActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrRevistaPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrRevistaPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrRevistaPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrRevistaPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrRevistaPrestamo().setVisible(true);
            }
        });
    }
    
    
    private void limpiar(){
        lblMosNom.setText("");
        lblMosApeP.setText("");
        lblMosApeM.setText("");
        lblMosCurp.setText("");
        lblMosRev.setText("");
        lblMosNum.setText("");
        /**
         * para poder limpiar las lbl de texto
         */
        
    }
    
    private void mensaje(){
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        String fechaComoCadena = sdf.format(new Date());
       
        lblMosFecha.setText(fechaComoCadena);//tener la fecha establecida
       /**
        * para que puedan poner la fecha en lbl
        */
    }
    
    private void llenarListaCliente(){
        RegistroCliente cli=new RegistroCliente();/**
         * llamamos la clase RegistroCliente
         */
        
        LinkedList<Cliente> Lista=cli.listaCliente();/**
         * generamos una lista ligada de Cliente, que le agregara la lista
         * de la clase RegistroCliente
         */
        for(int i=0; i<Lista.size(); i++){
            //Toma la informacion del toString para poner las etiquetas en la interfaz
            cmbNomCli.addItem(Lista.get(i));//se lo ingresamos como objetos, a combobox
        }
    }
    
    private void llenarListaRevista(){
        RegistroRevista cli=new RegistroRevista();/**
         * llamamos la clase registrorevitaa
         */
        
        LinkedList<Revistas> Lista=cli.listaR();/**
         * generamos una lista ligada de Revistas, que le agregara la lista
         * de la clase RegistroRevista
         */
        for(int i=0; i<Lista.size(); i++){
            //Toma la informacion del toString para poner las etiquetas en la interfaz
            cmbListaR.addItem(Lista.get(i));//se lo ingresamos como objetos, a combobox
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlRegistroPestrestamo;
    private javax.swing.JToggleButton btnLimpiar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistrarCkiente;
    private javax.swing.JComboBox<Revistas> cmbListaR;
    private javax.swing.JComboBox<Cliente> cmbNomCli;
    private javax.swing.JLabel lblApellidoM;
    private javax.swing.JLabel lblApellidoP;
    private javax.swing.JLabel lblClinoRe;
    private javax.swing.JLabel lblCurp;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblIngresarRev;
    private javax.swing.JLabel lblListaNombre;
    private javax.swing.JLabel lblListaRev;
    private javax.swing.JLabel lblMosApeM;
    private javax.swing.JLabel lblMosApeP;
    private javax.swing.JLabel lblMosCurp;
    private javax.swing.JLabel lblMosFecha;
    private javax.swing.JLabel lblMosNom;
    private javax.swing.JLabel lblMosNum;
    private javax.swing.JLabel lblMosRev;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblRegistroCliente;
    // End of variables declaration//GEN-END:variables
}
