/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uam.pvoe.sw.formas;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.LinkedList;
import javax.swing.JTextField;
import uam.pvoe.atributos.Editorial;
import uam.pvoe.operaciones.RegistroEditorial;
import uam.pvoe.operaciones.RegistroRevista;

/**
 *
 * @author Guerrero Cangas Sebastian
 * proyecto final 
 */
public class FrRegistrosRevista extends javax.swing.JFrame {

    /**
     * Creates new form FrRegistrosRevista
     */
    public FrRegistrosRevista() {
        initComponents();
        agruparSelecciones();
        limpiar();
        mensaje(); 
        llenarListaEditorial();
        numeros();
        /**
         * llamamos todas las funciones
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgPeriocidad = new javax.swing.ButtonGroup();
        pnlRegistroRevista = new javax.swing.JPanel();
        lblMosdi = new javax.swing.JLabel();
        lblListaEdito = new javax.swing.JLabel();
        cmbLista = new javax.swing.JComboBox<>();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblCantidad = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        lblTitulp = new javax.swing.JLabel();
        lblISBN = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtIsbn = new javax.swing.JTextField();
        lblEditorial = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        lblPeriocidad = new javax.swing.JLabel();
        rbMensual = new javax.swing.JRadioButton();
        rbBimestral = new javax.swing.JRadioButton();
        btnRegistrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlRegistroRevista.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Registro Revista\n"));

        lblListaEdito.setText("Lista de editorial");

        cmbLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbListaActionPerformed(evt);
            }
        });

        lblNumero.setText("Número");

        txtNumero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNumeroMouseClicked(evt);
            }
        });

        lblCantidad.setText("Cantidad");

        txtCantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCantidadMouseClicked(evt);
            }
        });

        lblTitulp.setText("Titulo");

        lblISBN.setText("ISBN");

        txtIsbn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIsbnMouseClicked(evt);
            }
        });
        txtIsbn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIsbnKeyTyped(evt);
            }
        });

        lblEditorial.setText("Editorial");

        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        lblPeriocidad.setText("Periocidad");

        rbMensual.setText("Mensual");

        rbBimestral.setText("Bimestreal");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegistroRevistaLayout = new javax.swing.GroupLayout(pnlRegistroRevista);
        pnlRegistroRevista.setLayout(pnlRegistroRevistaLayout);
        pnlRegistroRevistaLayout.setHorizontalGroup(
            pnlRegistroRevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroRevistaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRegistroRevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistroRevistaLayout.createSequentialGroup()
                        .addGroup(pnlRegistroRevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTitulp)
                            .addComponent(lblEditorial)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(txtNumero)
                            .addComponent(lblMosdi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(pnlRegistroRevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCantidad)
                            .addComponent(lblISBN)
                            .addComponent(lblListaEdito)
                            .addComponent(cmbLista, 0, 185, Short.MAX_VALUE)
                            .addComponent(txtIsbn)
                            .addComponent(txtCantidad)))
                    .addComponent(lblNumero)
                    .addGroup(pnlRegistroRevistaLayout.createSequentialGroup()
                        .addComponent(btnRegistrar)
                        .addGap(26, 26, 26)
                        .addComponent(btnLimpiar)
                        .addGap(18, 18, 18)
                        .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRegistroRevistaLayout.createSequentialGroup()
                        .addComponent(rbMensual)
                        .addGap(18, 18, 18)
                        .addComponent(rbBimestral))
                    .addComponent(lblPeriocidad))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        pnlRegistroRevistaLayout.setVerticalGroup(
            pnlRegistroRevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroRevistaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRegistroRevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulp)
                    .addComponent(lblISBN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRegistroRevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegistroRevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEditorial)
                    .addComponent(lblListaEdito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRegistroRevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMosdi))
                .addGap(32, 32, 32)
                .addGroup(pnlRegistroRevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumero)
                    .addComponent(lblCantidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRegistroRevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblPeriocidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRegistroRevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMensual)
                    .addComponent(rbBimestral))
                .addGap(18, 18, 18)
                .addGroup(pnlRegistroRevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnMenu))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(pnlRegistroRevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRegistroRevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void num(JTextField a){//para poder limitar a numeros 
        a.addKeyListener(new KeyAdapter(){
            public void keyTyped(KeyEvent e){
                char c = e.getKeyChar();
                if(!Character.isDigit(c) && c != '.'){
                    e.consume();
                }else if(c== '.' && txtNumero.getText().contains(".")){
                    e.consume();
                }else if(c== '.' && txtCantidad.getText().contains(".")){
                    e.consume();
                }else if(c== '.' && txtIsbn.getText().contains("-")){
                    e.consume();
                }
            }
        });
    }
    
    private void numeros(){
        num(txtCantidad);
        num(txtNumero);
        num(txtIsbn);
        /**
         * llamamos la caja de texto a la funcion solo para numeros
         */
    }
    
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
        mensaje();
        limpiarRb();
        /**
         * llamamos la funcion de limpiar y mensaje
         */
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        RegistroRevista rev = new RegistroRevista();
        
        String na = txtTitulo.getText();
        long na2 = Long.parseLong(txtIsbn.getText());
        String na3 = lblMosdi.getText();
        long p = Long.parseLong(txtNumero.getText());
        int p2 = Integer.parseInt(txtCantidad.getText());
        
        if(rbMensual.isSelected()==true){//por si esta activado
            String na4= "Mensual";
            rev.llenadoR(na, na2, na3, p, p2, na4);//mandamos a la clase
        }else if(rbBimestral.isSelected()==true){//por si esta activado el bimestral
            String na4="Bimestral";
            rev.llenadoR(na, na2, na3, p, p2, na4);//manamos a la clase
        }
        
        limpiar();
        limpiarRb();
        mensaje();
        /**
         * llamar las funciones de limpiar cajas y boton
         */
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtNumeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNumeroMouseClicked
        // TODO add your handling code here:
        String p = txtNumero.getText();
        if(p.equals("solo numeros >:c")){
            txtNumero.setText("");
        }
        /**
         * cuando salga en caja de texto ese mensaje 
         * al darle click se borrar
         */
                
    }//GEN-LAST:event_txtNumeroMouseClicked

    public void limpiarRb(){
        btgPeriocidad.clearSelection();//limpiar los radio boton
    }
    
    private void txtCantidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCantidadMouseClicked
        // TODO add your handling code here:
        String p = txtCantidad.getText();
        if(p.equals("solo numeros >:c")){
            txtCantidad.setText("");
        }
        /**
         * cuando salga en caja de texto ese mensaje 
         * al darle click se borrar
         */
        
    }//GEN-LAST:event_txtCantidadMouseClicked

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        FrMenu menu = new FrMenu();
        this.dispose();
        menu.setVisible(true);
        /**
         * abrimos el menu
         * y lo cerramos
         */
    }//GEN-LAST:event_btnMenuActionPerformed

    private void cmbListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbListaActionPerformed
        // TODO add your handling code here:
        int indice=cmbLista.getSelectedIndex(); //Recupera el indice empezando desde cero
        Editorial opcion =(Editorial) cmbLista.getSelectedItem();/**
         * la lista que tiene de seleccion el combobox de Editorial
         * podra cambiar y se guardara en el elemento 
         */  
        RegistroEditorial arc = new RegistroEditorial();/**
         * convocamos la funciones de la clase
         * RegistroEditorial
         */
        
        if(opcion.getNombreE().compareTo("--Selecciona el editorial--")==0){
            //para poder mantener limpia la caja de texto
            lblMosdi.setText("");
        }else{//mandamos el nombre a la caja de texto
            lblMosdi.setText(opcion.getNombreE());
        }
        if(opcion.getNombreE().compareTo("--Selecciona el editorial--")!=0){
            cmbLista.removeAllItems();
            llenarListaEditorial();
            /**
             * si es difirente se borra la caja de texto y vuelve cargar la lista
             */
        }
        
    }//GEN-LAST:event_cmbListaActionPerformed

    private void txtIsbnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIsbnKeyTyped
        // TODO add your handling code here:
        if(txtIsbn.getText().length() >= 20){
            evt.consume();
        }
        /**
         * para poder limitar la catidad de caracteres
         */
    }//GEN-LAST:event_txtIsbnKeyTyped

    private void txtIsbnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIsbnMouseClicked
        // TODO add your handling code here:
        String p = txtIsbn.getText();
        if(p.equals("solo numeros >:c")){
            txtIsbn.setText("");
        }
        /**
         * cuando salga en caja de texto ese mensaje 
         * al darle click se borrar
         */
    }//GEN-LAST:event_txtIsbnMouseClicked

    public void limpiar(){
        txtCantidad.setText("");
        lblMosdi.setText("");
        txtIsbn.setText("");
        txtTitulo.setText("");
        txtNumero.setText("");
        /**
         * limpiamos las cajas de texto
         */
    }
    
    public void agruparSelecciones(){
        btgPeriocidad.add(rbBimestral);
        btgPeriocidad.add(rbMensual);
        
        /**
         * para hacerlos mutuamente excluyentes
         */
    } 
    
    public void mensaje(){
        txtCantidad.setText("solo numeros >:c");
        txtNumero.setText("solo numeros >:c");
        txtIsbn.setText("solo numeros >:c");
       
        /**
         * mensajes que saldran desde un inicio en la caja
         */
    }
    
    public void llenarListaEditorial(){
        RegistroEditorial edi=new RegistroEditorial();/**
         * llamamos la clase RegistroEditorial
         */
        
        LinkedList<Editorial> Lista=edi.listaEditorial();/**
         * generamos una lista ligada de editoriales, que le agregara la lista
         * de la clase RegistroEditorial
         */
        for(int i=0; i<Lista.size(); i++){
            //Toma la informacion del toString para poner las etiquetas en la interfaz
            cmbLista.addItem(Lista.get(i));//se lo ingresamos como objetos, a combobox
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrRegistrosRevista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrRegistrosRevista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrRegistrosRevista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrRegistrosRevista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrRegistrosRevista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgPeriocidad;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<Editorial> cmbLista;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblEditorial;
    private javax.swing.JLabel lblISBN;
    private javax.swing.JLabel lblListaEdito;
    private javax.swing.JLabel lblMosdi;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblPeriocidad;
    private javax.swing.JLabel lblTitulp;
    private javax.swing.JPanel pnlRegistroRevista;
    private javax.swing.JRadioButton rbBimestral;
    private javax.swing.JRadioButton rbMensual;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtIsbn;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
